app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: MisakraNET
publisher_url: https://github.com/mxiaoyuer123/Hiddify-with-V2board
display_name: MisakraNET
executable_name: MisakraNET.exe
output_base_file_name: MisakraNET.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\MisakraNET"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas
